apiVersion: apps/v1
kind: Deployment
metadata:
  name: cup-process
  namespace: cup
spec:
  selector:
    matchLabels:
      app: cup-process
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: cup-process
        logtail: 'true'
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: cup-process
          image: cup:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
            timeoutSeconds: 2
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 3
            timeoutSeconds: 2
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 3
            timeoutSeconds: 2
            failureThreshold: 20
          resources:
            requests:
              cpu: 100m
              memory: 500M
            limits:
              cpu: 1000m
              memory: 500M
          env:
            - name: aws.sqs.consumers
              value: 'TRIGGER,CACHE_RESPONSE,VEHICLE_DATA_RESPONSE'
            - name: aws.sqs.producers
              value: 'CACHE_REQUEST,HISTORY,PROCESSED,VEHICLE_DATA_REQUEST'
            - name: application.ext-request-proxy
              value: 'false'
            - name: application.history
              value: 'false'
            - name: logging.level.root
              value: 'INFO'
            - name: management.metrics.tags.application
              value: 'cup-process'
