apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: cup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16.0-alpine3.18
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: data-volume
              mountPath: /var/lib/postgres/data
            - name: sql-startup
              mountPath: /docker-entrypoint-initdb.d/
              readOnly: true
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: postgres-persistent-volume-claim
        - name: sql-startup
          configMap:
            name: sql-startup