apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-persistent-volume
  namespace: cup
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data"