apiVersion: v1
kind: Service
metadata:
  name: cup-rollout
  namespace: cup
spec:
  selector:
    app: cup-rollout
  type: NodePort
  ports:
    - name: "cup-rollout"
      port: 8080
      targetPort: 8080
      nodePort: 30084
