apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cup
  name: maha-k8s-api
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "get", "watch", "list", "update" , "patch" ]