apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: maha-k8s-api
  namespace: cup
subjects:
  - kind: ServiceAccount
    name: maha
    apiGroup: ""
    namespace: cup
roleRef:
  kind: Role
  name: maha-k8s-api # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io