apiVersion: apps/v1
kind: Deployment
metadata:
  name: cup-history
  namespace: cup
spec:
  selector:
    matchLabels:
      app: cup-history
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: cup-history
        logtail: 'true'
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: cup-history
          image: cup:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
            timeoutSeconds: 2
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 3
            timeoutSeconds: 2
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 3
            timeoutSeconds: 2
            failureThreshold: 20
          resources:
            requests:
              cpu: 100m
              memory: 500M
            limits:
              cpu: 1000m
              memory: 500M
          env:
            - name: aws.sqs.consumers
              value: 'HISTORY'
            - name: aws.sqs.producers
              value: ''
            - name: application.ext-request-proxy
              value: 'false'
            - name: application.history
              value: 'true'
            - name: logging.level.root
              value: 'INFO'
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: spring.datasource.url
              value: jdbc:postgresql://postgres.cup:5432/$(POSTGRES_DB)
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: management.metrics.tags.application
              value: 'cup-history'

