apiVersion: v1
kind: Service
metadata:
  name: cup-history
  namespace: cup
spec:
  selector:
    app: cup-history
  type: NodePort
  ports:
    - name: "cup-history"
      port: 8080
      targetPort: 8080
      nodePort: 30085
