apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-k8s-api
rules:
  - apiGroups: [ "" ]
    resources:
      - nodes
      - nodes/proxy
      - namespaces
      - services
      - pods
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "get", "watch", "list" ]