apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: cup
data:
  prometheus.rules: |-
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
      scrape_timeout: 4s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers:
        - scheme: http
          static_configs:
            - targets:
                - "alertmanager.monitoring.svc:9093"
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: [ "localhost:9090" ]
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: [ 'kube-state-metrics.kube-system.svc.cluster.local:8080' ]
      - job_name: 'maha'
        static_configs:
          - targets: [ "host.docker.internal:30070" ]
        metrics_path: /actuator/prometheus
      - job_name: 'cup-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [ __meta_kubernetes_pod_annotation_prometheus_io_scrape ]
            action: keep
            regex: true
          - source_labels: [ __meta_kubernetes_pod_name ]
            action: replace
            target_label: 'pod_name'
        static_configs:
          - targets:
              - "host.docker.internal:30080"
              - "host.docker.internal:30081"
              - "host.docker.internal:30082"
              - "host.docker.internal:30083"
              - "host.docker.internal:30084"
              - "host.docker.internal:30085"
        metrics_path: /actuator/prometheus
        
