apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: cup
  name: cup-rollout-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cup-rollout
  minReplicas: 1
  maxReplicas: 20
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
        - periodSeconds: 5
          type: Pods
          value: 1
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - periodSeconds: 5
          type: Pods
          value: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60

