apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana.ini
  labels:
    name: grafana.ini
    app: grafana
  namespace: cup
data:
  grafana.ini: |-
    [auth.anonymous]
    enabled = true
    # Organization name that should be used for unauthenticated users
    org_name = Main Org.
    # Role for unauthenticated users, other valid values are `Editor` and `Admin`
    org_role = Admin
    # Hide the Grafana version text from the footer and help tooltip for unauthenticated users (default: false)
    hide_version = true
    [dashboards]
    min_refresh_interval = 1s