apiVersion: v1
kind: ConfigMap
metadata:
  name: datasource.yml
  labels:
    name: datasource.yml
    app: grafana
  namespace: cup
data:
  datasource.yml: |-
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        # Access mode - proxy (server in the UI) or direct (browser in the UI).
        url: http://host.docker.internal:30000
        jsonData:
          timeInterval: 5s
          httpMethod: POST
          manageAlerts: true
          prometheusType: Prometheus
          prometheusVersion: 2.45.1
          cacheLevel: 'High'
          disableRecordingRules: false
          incrementalQueryOverlapWindow: 10m
          exemplarTraceIdDestinations:
            # Field with internal link pointing to data source in Grafana.
            # datasourceUid value can be anything, but it should be unique across all defined data source uids.
            - datasourceUid: prometheus_uid
              name: traceID
            
            # Field with external link.
            - name: traceID
              url: 'http://localhost:30000'