{
 "title": "Messaging and scaling",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Consumed by pod from queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "application:consumed_from_queue_total",
     "legendFormat": "{{pod_name}} from {{queue}}"
    }
   ]
  },
  {
   "title": "Produced by pod to queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "application:produced_to_queue_total{application=~\"cup.+\"}",
     "legendFormat": "{{pod_name}} to {{queue}}"
    }
   ]
  },
  {
   "title": "Number of messages in queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "application:number_of_messages_in_queue",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "HPA CPU percentage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_target_metric{metric_name=\"cpu\", metric_target_type=\"utilization\"}",
     "legendFormat": "{{horizontalpodautoscaler}}"
    }
   ]
  },
  {
   "title": "Number of pods running",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(container) (kube_pod_container_status_running{pod=~\"cup-.+\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Number of pods ready",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(container) (kube_pod_container_status_ready{pod=~\"cup-.+\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Square Size for screenshots",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consumed by pod from queue",
     "type": "timeseries",
     "gridPos": { "h": 22, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "application:consumed_from_queue_total",
       "legendFormat": "{{pod_name}} from {{queue}}"
      }
     ]
    },
    {
     "title": "Produced by pod to queue",
     "type": "timeseries",
     "gridPos": { "h": 22, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "application:produced_to_queue_total{application=~\"cup.+\"}",
       "legendFormat": "{{pod_name}} to {{queue}}"
      }
     ]
    },
    {
     "title": "Number of messages in queue",
     "type": "timeseries",
     "gridPos": { "h": 22, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "application:number_of_messages_in_queue",
       "legendFormat": "{{queue}}"
      }
     ]
    },
    {
     "title": "HPA CPU percentage",
     "type": "timeseries",
     "gridPos": { "h": 22, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kube_horizontalpodautoscaler_status_target_metric{metric_name=\"cpu\", metric_target_type=\"utilization\"}",
       "legendFormat": "{{horizontalpodautoscaler}}"
      }
     ]
    },
    {
     "title": "Number of pods running",
     "type": "timeseries",
     "gridPos": { "h": 22, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(container) (kube_pod_container_status_running{pod=~\"cup-.+\"})",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "Number of pods ready",
     "type": "timeseries",
     "gridPos": { "h": 22, "w": 12, "x": 12, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(container) (kube_pod_container_status_ready{pod=~\"cup-.+\"})",
       "legendFormat": "{{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Old",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consumed by service from queue",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "sum by(application, queue) (application:consumed_from_queue_total)",
       "legendFormat": "Consumed by {{application}} from {{queue}}"
      }
     ]
    },
    {
     "title": "Produced by service to queue",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(application, queue) (application:produced_to_queue_total{application=~\"cup.+\"})",
       "legendFormat": "Produced by {{application}} to {{queue}}"
      }
     ]
    }
   ]
  }
 ]
}