apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: cup
spec:
  selector:
    app: localstack
  type: NodePort
  ports:
    - name: "edge"
      port: 4566
      targetPort: 4566
      nodePort: 30001
    - name: "ui"
      port: 8080
      targetPort: 8080
      nodePort: 30002
